# Generated by Django 2.0.3 on 2018-04-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shook', '0002_shake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shake',
            name='accepted_complete',
        ),
        migrations.RemoveField(
            model_name='shake',
            name='accepted_delete',
        ),
        migrations.RemoveField(
            model_name='shake',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shake',
            name='finished_date',
        ),
        migrations.RemoveField(
            model_name='shake',
            name='proposed_accepted',
        ),
        migrations.RemoveField(
            model_name='shake',
            name='proposed_complete',
        ),
        migrations.RemoveField(
            model_name='shake',
            name='proposed_delete',
        ),
        migrations.AddField(
            model_name='shake',
            name='accepter_status',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.AddField(
            model_name='shake',
            name='proposer_status',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
