# Generated by Django 2.0.3 on 2018-04-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shook', '0003_auto_20180410_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shake',
            name='proposer_status',
            field=models.CharField(default='proposed', max_length=100),
        ),
        migrations.AlterField(
            model_name='shake',
            name='status',
            field=models.CharField(default='proposed', max_length=100),
        ),
    ]
